export const HTTP_START = "HTTP_START";
export const HTTP_SUCCESS = "HTTP_SUCCESS";
export const HTTP_FAILURE = "HTTP_FAILURE";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const ISSUE_ADD = "ISSUE_ADD";
export const ISSUE_ADD_SUCCESS = "ISSUE_ADD_SUCCESS";
export const ISSUE_LIST = "ISSUE_LIST";
export const ISSUE_LIST_SUCCESS = "ISSUE_LIST_SUCCESS";
export const ISSUE_GET = "ISSUE_GET";
export const ISSUE_GET_SUCCESS = "ISSUE_GET_SUCCESS";
export const ISSUE_CLEAR = "ISSUE_CLEAR";

export const TEMPLATE_GET = "TEMPLATE_GET";
export const TEMPLATE_GET_SUCCESS = "TEMPLATE_GET_SUCCESS";

export const PROJECT_ADD = "PROJECT_ADD";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_LIST = "PROJECT_LIST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_GET = "PROJECT_GET";
export const PROJECT_GET_SUCCESS = "PROJECT_GET_SUCCESS";
export const PROJECT_CLEAR = "PROJECT_CLEAR";
export const PROJECT_REARRANGE = "PROJECT_REARRANGE";
