export const HTTP_START = "HTTP_START";
export const HTTP_SUCCESS = "HTTP_SUCCESS";
export const HTTP_FAILURE = "HTTP_FAILURE";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const ISSUE_ADD = "ISSUE_ADD";
export const ISSUE_ADD_SUCCESS = "ISSUE_ADD_SUCCESS";
export const ISSUE_LIST = "ISSUE_LIST";
export const ISSUE_LIST_SUCCESS = "ISSUE_LIST_SUCCESS";
